version: '3'
services:
  container:
    build:
      context: .
      dockerfile: Dockerfile
    image: cnt
    volumes:
      - .:/app

  test-install:
    build:
      context: .
      dockerfile: Dockerfile
    image: cnt
    volumes:
      - .:/app
    command: python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name installtest --gamma 0.999
